pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=build-workflow-complete
      - label!=hold
    actions:
      merge:
        method: merge

  - name: automatic merge for main with > 1 approved reviews, all requested reviews have given feedback, not held, and CI is successful
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - base=main
      - label!=hold
      - check-success=DCO
      - or:
        - check-success=Header rules - nexodus-docs
        - check-neutral=Header rules - nexodus-docs
      - or:
        - check-success=Mixed content - nexodus-docs
        - check-neutral=Mixed content - nexodus-docs
      - or:
        - check-success=Pages changed - nexodus-docs
        - check-neutral=Pages changed - nexodus-docs
      - or:
        - check-success=Redirect rules - nexodus-docs
        - check-neutral=Redirect rules - nexodus-docs
      - or:
        - check-success=netlify/nexodus-docs/deploy-preview
        - check-neutral=netlify/nexodus-docs/deploy-preview
      - or:
        - label=has-design
        - label=no-design-required
      - or:
        - label=has-docs
        - label=no-docs-required
      - or:
        - label=has-tests
        - label=no-tests-required
      # If files are changed in .github/, the actionlint check must pass
      - or:
        - and:
          # regex should match the one in .github/workflows/actionlint.yml
          - files~=.github/.*$
          - check-success=actionlint
        - -files~=.github/.*$
      - or:
        # PRs that include doc changes should also pass the markdown-lint check
        - and:
          - check-success=build-workflow-complete
          - files~=\.md$
          - check-success=markdown-lint
        # PRs that do not include doc changes only need to pass the build workflow
        - and:
          - check-success=build-workflow-complete
          - -files~=\.md$
        # PRs that do not run the build workflow (e.g. docs-only changes) must have a successful markdown-lint check
        - and:
          - check-success=markdown-lint
          # Must stay in sync with the paths in .github/workflows/docs.yml and .github/workflows/build.yml
          - -files~=^(?!.*\.md$)(?!.*\.png$)(?!.*\.gitignore$)(?!\.vscode\/).*$
    actions:
      merge:
        method: merge

  - name: Warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}}, this pull request is now in conflict and requires a rebase."
      label:
        add:
          - needs-rebase
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - needs-rebase

  # Give a hint via label when no docs label has been applied
  - name: Label when docs label is missing
    conditions:
      - -label=has-docs
      - -label=no-docs-required
      - -author=dependabot[bot]
      - -draft
    actions:
      label:
        add:
          - missing-docs-label
  - name: Remove label when docs label is present
    conditions:
      - or:
        - label=has-docs
        - label=no-docs-required
        - author=dependabot[bot]
        - draft
    actions:
      label:
        remove:
          - missing-docs-label

  # Give a hint via label when no design doc label has been applied
  - name: Label when design doc label is missing
    conditions:
      - -label=has-design
      - -label=no-design-required
      - -author=dependabot[bot]
      - -draft
    actions:
      label:
        add:
          - missing-design-label
  - name: Remove label when design doc label is present
    conditions:
      - or:
        - label=has-design
        - label=no-design-required
        - author=dependabot[bot]
        - draft
    actions:
      label:
        remove:
          - missing-design-label

  # Give a hint via label when no tests label has been applied
  - name: Label when tests label is missing
    conditions:
      - -label=has-tests
      - -label=no-tests-required
      - -author=dependabot[bot]
      - -draft
    actions:
      label:
        add:
          - missing-tests-label
  - name: Remove label when tests label is present
    conditions:
      - or:
        - label=has-tests
        - label=no-tests-required
        - author=dependabot[bot]
        - draft
    actions:
      label:
        remove:
          - missing-tests-label

