apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: database
spec:
  image: quay.io/nexodus/crunchy-postgres:ubi8-14.6-0
  postgresVersion: 14
  instances:
    - name: instance1
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 2Gi
      resources:
        limits:
          cpu: 500m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      sidecars:
        replicaCertCopy:
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
  backups:
    pgbackrest:
      image: quay.io/nexodus/crunchy-pgbackrest:ubi8-2.41-0
      global:
        # 7 Day Retention
        repo1-retention-full: "7"
        repo1-retention-full-type: time
      sidecars:
        pgbackrest:
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
        pgbackrestConfig:
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      repoHost:
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 200m
      repos:
        - name: repo1
          schedules:
            # Sunday 4:42am
            full: "42 4 * * 0"
            # Monday-Sat 4:42am
            differential: "42 4 * * 1-6"
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
  users:
    - name: ipam
      databases:
        - ipam
      options: "NOSUPERUSER"
    - name: apiserver
      databases:
        - apiserver
      options: "NOSUPERUSER"
    - name: keycloak
      databases:
        - keycloak
      options: "NOSUPERUSER"
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: 100
          shared_buffers: 128MB
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.19-3
      replicas: 1
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 200Mi
      config:
        global:
          pool_mode: session
          max_client_conn: "100"
          default_pool_size: "30"
        databases:
          ipam: "host=database-primary port=5432 pool_size=15 reserve_pool=5 max_db_connections=20"
          apiserver: "host=database-primary port=5432 pool_size=35 reserve_pool=5 max_db_connections=40"
          keycloak: "host=database-primary port=5432 pool_size=35 reserve_pool=5 max_db_connections=40"
