# See: https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret#config-secret-discovery-service
resources:

  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: nexodus-cert
    tls_certificate:
      certificate_chain:
        filename: /configs/envoy-certs/nexodus-cert/tls.crt
      private_key:
        filename: /configs/envoy-certs/nexodus-cert/tls.key
      watched_directory:
        path: /configs/envoy-certs/nexodus-cert
