apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana-access
  namespace: nexodus-monitoring
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: grafana-tls
spec:
  host: nexodus-grafana.apps.platform-sts.pcbk.p1.openshiftapps.com
  port:
    targetPort: 3000
  tls:
    termination: edge
  to:
    kind: Service
    name: nexodus-grafana-service
    weight: 100
  wildcardPolicy: None
