# roles get branched from here
# Note: Optionally comment out any sections to pick and choose what gets run

# Deploy the VMs
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - role: setup-ec2

# Deploy and start the agent
- hosts: nexodusNodes
  vars_files:
    - vars.yml
  roles:
    - role: deploy-mesh

# Deploy and start the relay server (--relay-node)
- hosts: relayNode
  vars_files:
    - vars.yml
  roles:
    - role: deploy-relay

# Deploy and start the relay only agents (--relay-only)
- hosts: nexodusRelayNodes
  vars_files:
    - vars.yml
  roles:
    - role: deploy-mesh

# Validate nodes by running a connectivity test from the spoke node for QA e2e deployment
- hosts:  nexodusNodes
  vars_files:
    - vars.yml
  roles:
    - role: validate-connectivity

# Collect nexd logs at the end
- hosts: nexodusNodes
  vars_files:
    - vars.yml
  roles:
    - role: collect-logs

- hosts: nexodusRelayNodes
  vars_files:
    - vars.yml
  roles:
    - role: collect-logs

- hosts: relayNode
  vars_files:
    - vars.yml
  roles:
    - role: collect-logs