apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../openshift
  - sealed-secret.yaml
  - sealed-secret-smtp.yaml
namespace: nexodus-qa
configMapGenerator:
  - behavior: replace
    files:
      - files/nexodus.json
    name: realm
  - behavior: replace
    literals:
      - hostname=auth.qa.nexodus.io
      - frontend-url=https://qa.nexodus.io
      - redirect-url=https://api.qa.nexodus.io/web
    name: auth-config
  - behavior: merge
    literals:
      - APIPROXY_API_URL=https://api.qa.nexodus.io
      - APIPROXY_OIDC_URL=https://auth.qa.nexodus.io/realms/nexodus
      - APIPROXY_API_DOMAIN=api.qa.nexodus.io
      - APIPROXY_WEB_DOMAIN=qa.nexodus.io
        APIPROXY_AUTH_DOMAIN=auth.qa.nexodus.io
      - APIPROXY_WEB_ORIGINS=https://qa.nexodus.io
      - ENVOY_COMP_LOG_LEVEL=upstream:info,http:debug,router:debug,jwt:debug
    name: apiproxy
  - behavior: merge
    literals:
      - NEXAPI_URL=https://api.qa.nexodus.io
      - NEXAPI_OIDC_URL=https://auth.qa.nexodus.io/realms/nexodus
      - NEXAPI_DOMAIN=api.qa.nexodus.io
      - NEXAPI_ORIGINS=https://qa.nexodus.io
      - NEXAPI_ENVIRONMENT=qa
      - NEXAPI_DEBUG=0
    name: apiserver
patches:
  # Update the dns names for the certificates
  - target:
      kind: Certificate
      name: nexodus-cert
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - qa.nexodus.io
          - api.qa.nexodus.io
          - auth.qa.nexodus.io
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.qa.nexodus.io
    target:
      kind: Ingress
      name: apiproxy
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: auth.qa.nexodus.io
    target:
      kind: Ingress
      name: auth
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: qa.nexodus.io
    target:
      kind: Ingress
      name: frontend
