---
- name: Initialize the PR or Branch on the api-server
  hosts: localhost
  gather_facts: true
  vars:
    repo_dir: /home/ubuntu/nexodus
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure nexodus directory is absent (remove it)
      file:
        path: "{{ repo_dir }}"
        state: absent
      delegate_to: "{{ target_host }}"

    - name: Clone nexodus repository
      git:
        repo: 'https://github.com/nexodus-io/nexodus.git'
        dest: "{{ repo_dir }}"
      delegate_to: "{{ target_host }}"

    - name: Checkout the appropriate branch or PR
      command:
        cmd: "{% if pr_or_branch == 'main' %}git checkout main{% else %}gh pr checkout {{ pr_or_branch }}{% endif %}"
        chdir: "{{ repo_dir }}"
      delegate_to: "{{ target_host }}"
      ignore_errors: true

    - name: Prune System
      ansible.builtin.command:
        cmd: docker system prune -f
      become: true

    - name: Redeploy
      ansible.builtin.shell:
        cmd: make redeploy
        chdir: "{{ repo_dir }}"
      delegate_to: "{{ target_host }}"

    - name: Recreate DB
      ansible.builtin.shell:
        cmd: make recreate-db
        chdir: "{{ repo_dir }}"
      delegate_to: "{{ target_host }}"
