---
- name: Initialize the PR or Branch on the api-server
  hosts: localhost
  gather_facts: true
  vars:
    repo_dir: /home/ubuntu/nexodus
  tasks:
    - name: Ensure nexodus directory is absent (remove it)
      file:
        path: "{{ repo_dir }}"
        state: absent
      delegate_to: "{{ target_host }}"

    - name: Clone nexodus repository
      git:
        repo: 'https://github.com/nexodus-io/nexodus.git'
        dest: "{{ repo_dir }}"
      delegate_to: "{{ target_host }}"

    - name: Checkout the appropriate branch or PR
      command:
        cmd: "{% if pr_or_branch == 'main' %}git checkout main{% else %}gh pr checkout {{ pr_or_branch }}{% endif %}"
        chdir: "{{ repo_dir }}"
      delegate_to: "{{ target_host }}"
      ignore_errors: true

    - name: Prune System
      ansible.builtin.command:
        cmd: docker system prune -f
      become: true

    - name: Replace the current kind images with this branch
      make:
        chdir: "{{ repo_dir }}"
        target: images
      delegate_to: "{{ target_host }}"

    - name: Load images
      make:
        chdir: "{{ repo_dir }}"
        target: load-images
      delegate_to: "{{ target_host }}"

    - name: Recreate DB asynchronously
      command: make recreate-db
      args:
        chdir: "{{ repo_dir }}"
      delegate_to: "{{ target_host }}"
      async: 360
      poll: 30  # Check the task status every 30 seconds
      register: recreate_db_result

    - name: Wait for the Recreate DB asynchronous task to complete
      async_status:
        jid: "{{ recreate_db_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
