apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-ds
spec:
  instanceSelector:
    matchLabels:
      dashboards: "nexodus-grafana"
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-operated:9090
    isDefault: true
    editable: false
    jsonData:
      tlsSkipVerify: true
      timeInterval: "5s"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo-ds
spec:
  instanceSelector:
    matchLabels:
      dashboards: "nexodus-grafana"
  datasource:
    name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      tracesToLogs:
        datasourceUid: 'Loki'
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki-ds
spec:
  instanceSelector:
    matchLabels:
      dashboards: "nexodus-grafana"
  datasource:
    name: Loki
    type: loki
    access: proxy
    url: http://loki:3100/
    isDefault: false
    editable: false
