apiVersion: integreatly.org/v1beta1
kind: Grafana
metadata:
  name: nexodus-grafana
spec:
  client:
    preferService: true
  ingress:
    enabled: true
    hostname: grafana.127.0.0.1.nip.io
    path: /
    pathType: Prefix
  config:
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: "admin"
      admin_password: "floofykittens"
    server:
      root_url: http://grafana.127.0.0.1.nip.io
    auth:
      disable_login_form: false
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
  dashboardLabelSelector:
    - matchExpressions:
        - key: app.kubernetes.io/component
          operator: In
          values: [grafana]
