---
# tasks file for deploy-relay
- name: Update repo cache
  become: yes
  apt:
    update_cache: yes

- name: Install dependencies
  become: yes
  apt:
    name:
      - wireguard
      - fping
      - iperf3
      - mkcert
      - nftables
    state: latest

# Remove with https://github.com/nexodus-io/nexodus/issues/789
- name: Remove the stored token
  become: yes
  shell: |
    rm /var/lib/nexd/state.json
  ignore_errors: yes

- name: Create the certs dir
  shell: |
    mkdir -p .certs

- name: Copy rootCA.pem
  copy:
    src: rootCA.pem
    dest: .certs/
    mode: 0644

- name: mkcert
  shell: |
    CAROOT=/home/{{ ansible_user }}/.certs mkcert -install

- name: Kill any existing nexd process from previous runs
  shell: |
    sudo killall nexd 2> /dev/null
  ignore_errors: yes

# Optionally clean all remnants of a previous run (the agent will do this as well)
#- name: Delete wg0
#  become: yes
#  shell: |
#    sudo ip link del wg0
#  ignore_errors: yes

- name: Delete hosts file
  become: yes
  shell: |
    sudo rm -rf /etc/hosts
    sudo touch /etc/hosts
  ignore_errors: yes

- name: Add controller host entry
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      127.0.0.1 localhost
      ::1 ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts
      {{ controller_address }} auth.try.nexodus.127.0.0.1.nip.io api.try.nexodus.127.0.0.1.nip.io try.nexodus.127.0.0.1.nip.io

- name: Download the Nexodus Agent Binary
  shell: |
    sudo curl {{ nexodus_binary }} --output /usr/local/sbin/nexd
    sudo chmod +x /usr/local/sbin/nexd

- name: Running The following nexd command
  debug:
    msg: "nexd --stun --username '{{ nexodus_auth_uid }}' --password '{{ nexodus_auth_password }}' relay {{ nexodus_url }}"

- name: Attach the Relay Node to the Controller
  become: yes
  shell: |
    echo "Running command: nexd --stun --username {{ nexodus_auth_uid }} --password {{ nexodus_auth_password }} relay {{ nexodus_url }}" > nexodus-logs.txt
    NEXD_LOGLEVEL=debug nexd \
    --stun \
    --username '{{ nexodus_auth_uid }}' \
    --password '{{ nexodus_auth_password }}' \
    relay \
    {{ nexodus_url }} >> nexodus-logs.txt 2>&1 &

- name: Pause for 30 seconds for the onboard to complete to scrape the logs
  pause:
    seconds: 30

- name: Get IPv4 address of wg0
  shell: "ip -4 addr show wg0 | grep -oP '(?<=inet\\s)\\d+(\\.\\d+){3}'"
  register: ipv4_address_result
  ignore_errors: yes

- name: wg dump to logs
  become: yes
  shell: |
    printf "\n\n====== WG Dump from Node: {{ inventory_hostname }} wg0 Addr: {{ ipv4_address_result }} ======\n" >> /home/{{ ansible_user }}/nexodus-logs.txt
    wg show wg0 dump >> /home/{{ ansible_user }}/nexodus-logs.txt
  ignore_errors: yes

- name: Display the nexd logs to stdout
  become: yes
  shell: |
    cat /home/{{ ansible_user }}/nexodus-logs.txt

- name: Copy file from remote host to localhost
  fetch:
    src: /home/{{ ansible_user }}/nexodus-logs.txt
    dest: ./nexd-logs/{{ ansible_hostname }}-relay-node-nexodus-logs.txt
    flat: yes
  ignore_errors: yes
