#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 2595f7eb28d62a7d6d6c42a448e28c49245f136d
  - name: quay.io/nexodus/envsubst
    newTag: 2595f7eb28d62a7d6d6c42a448e28c49245f136d
  - name: quay.io/nexodus/frontend
    newTag: 2595f7eb28d62a7d6d6c42a448e28c49245f136d
  - name: quay.io/nexodus/go-ipam
    newTag: 2595f7eb28d62a7d6d6c42a448e28c49245f136d
