#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 1dfd00abe400d3a195d2f8107861ebc65ffbfc3b
  - name: quay.io/nexodus/envsubst
    newTag: 1dfd00abe400d3a195d2f8107861ebc65ffbfc3b
  - name: quay.io/nexodus/frontend
    newTag: 1dfd00abe400d3a195d2f8107861ebc65ffbfc3b
  - name: quay.io/nexodus/go-ipam
    newTag: 1dfd00abe400d3a195d2f8107861ebc65ffbfc3b
