#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: c33e25093e93bf51d4e6eedd53087852238ec662
  - name: quay.io/nexodus/envsubst
    newTag: c33e25093e93bf51d4e6eedd53087852238ec662
  - name: quay.io/nexodus/frontend
    newTag: c33e25093e93bf51d4e6eedd53087852238ec662
  - name: quay.io/nexodus/go-ipam
    newTag: c33e25093e93bf51d4e6eedd53087852238ec662
