#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: a4501144d790bd324f832e93283082c5015a9e06
  - name: quay.io/nexodus/envsubst
    newTag: a4501144d790bd324f832e93283082c5015a9e06
  - name: quay.io/nexodus/frontend
    newTag: a4501144d790bd324f832e93283082c5015a9e06
  - name: quay.io/nexodus/go-ipam
    newTag: a4501144d790bd324f832e93283082c5015a9e06
