#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: b6b830871accca15b9d6895016802bbc4c5b5538
  - name: quay.io/nexodus/envsubst
    newTag: b6b830871accca15b9d6895016802bbc4c5b5538
  - name: quay.io/nexodus/frontend
    newTag: b6b830871accca15b9d6895016802bbc4c5b5538
  - name: quay.io/nexodus/go-ipam
    newTag: b6b830871accca15b9d6895016802bbc4c5b5538
