#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: fa0b037292a407d6e367215fe316e73a65d032b3
  - name: quay.io/nexodus/envsubst
    newTag: fa0b037292a407d6e367215fe316e73a65d032b3
  - name: quay.io/nexodus/frontend
    newTag: fa0b037292a407d6e367215fe316e73a65d032b3
  - name: quay.io/nexodus/go-ipam
    newTag: fa0b037292a407d6e367215fe316e73a65d032b3
