#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 1c5b0774d96d2b7b9174755ae4958b7c46ffc0d9
  - name: quay.io/nexodus/envsubst
    newTag: 1c5b0774d96d2b7b9174755ae4958b7c46ffc0d9
  - name: quay.io/nexodus/frontend
    newTag: 1c5b0774d96d2b7b9174755ae4958b7c46ffc0d9
  - name: quay.io/nexodus/go-ipam
    newTag: 1c5b0774d96d2b7b9174755ae4958b7c46ffc0d9
