#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 225b1e5889a60ae52d8b392a6f6f576ff004af51
  - name: quay.io/nexodus/envsubst
    newTag: 225b1e5889a60ae52d8b392a6f6f576ff004af51
  - name: quay.io/nexodus/frontend
    newTag: 225b1e5889a60ae52d8b392a6f6f576ff004af51
  - name: quay.io/nexodus/go-ipam
    newTag: 225b1e5889a60ae52d8b392a6f6f576ff004af51
