#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 9630af44813c0ce7401e4603ceec35aa721acdce
  - name: quay.io/nexodus/envsubst
    newTag: 9630af44813c0ce7401e4603ceec35aa721acdce
  - name: quay.io/nexodus/frontend
    newTag: 9630af44813c0ce7401e4603ceec35aa721acdce
  - name: quay.io/nexodus/go-ipam
    newTag: 9630af44813c0ce7401e4603ceec35aa721acdce
