#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: b6ae331e613024eb1b01c1ebf885ba7e5887d219
  - name: quay.io/nexodus/envsubst
    newTag: b6ae331e613024eb1b01c1ebf885ba7e5887d219
  - name: quay.io/nexodus/frontend
    newTag: b6ae331e613024eb1b01c1ebf885ba7e5887d219
  - name: quay.io/nexodus/go-ipam
    newTag: b6ae331e613024eb1b01c1ebf885ba7e5887d219
