#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: b32c04ef85cf5121d11f0bcc8ef8ce23ca3802f0
  - name: quay.io/nexodus/envsubst
    newTag: b32c04ef85cf5121d11f0bcc8ef8ce23ca3802f0
  - name: quay.io/nexodus/frontend
    newTag: b32c04ef85cf5121d11f0bcc8ef8ce23ca3802f0
  - name: quay.io/nexodus/go-ipam
    newTag: b32c04ef85cf5121d11f0bcc8ef8ce23ca3802f0
