#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 6f19a696830afd104bac29ece3ec4b6f35b0d548
  - name: quay.io/nexodus/envsubst
    newTag: 6f19a696830afd104bac29ece3ec4b6f35b0d548
  - name: quay.io/nexodus/frontend
    newTag: 6f19a696830afd104bac29ece3ec4b6f35b0d548
  - name: quay.io/nexodus/go-ipam
    newTag: 6f19a696830afd104bac29ece3ec4b6f35b0d548
