#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 8b97b1629326ee7cda690eab111de73646bb0453
  - name: quay.io/nexodus/envsubst
    newTag: 8b97b1629326ee7cda690eab111de73646bb0453
  - name: quay.io/nexodus/frontend
    newTag: 8b97b1629326ee7cda690eab111de73646bb0453
  - name: quay.io/nexodus/go-ipam
    newTag: 8b97b1629326ee7cda690eab111de73646bb0453
