#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 5d6e9ffeb58696691fa968ccc595d0959ef7f80d
  - name: quay.io/nexodus/envsubst
    newTag: 5d6e9ffeb58696691fa968ccc595d0959ef7f80d
  - name: quay.io/nexodus/frontend
    newTag: 5d6e9ffeb58696691fa968ccc595d0959ef7f80d
  - name: quay.io/nexodus/go-ipam
    newTag: 5d6e9ffeb58696691fa968ccc595d0959ef7f80d
