#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: de769b521d7a7ce26ad94ed928da8efda76f64e6
  - name: quay.io/nexodus/envsubst
    newTag: de769b521d7a7ce26ad94ed928da8efda76f64e6
  - name: quay.io/nexodus/frontend
    newTag: de769b521d7a7ce26ad94ed928da8efda76f64e6
  - name: quay.io/nexodus/go-ipam
    newTag: de769b521d7a7ce26ad94ed928da8efda76f64e6
