#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: a35150fcd144434a3feb565bd8a6b7d79639dbdb
  - name: quay.io/nexodus/envsubst
    newTag: a35150fcd144434a3feb565bd8a6b7d79639dbdb
  - name: quay.io/nexodus/frontend
    newTag: a35150fcd144434a3feb565bd8a6b7d79639dbdb
  - name: quay.io/nexodus/go-ipam
    newTag: a35150fcd144434a3feb565bd8a6b7d79639dbdb
