#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 41d9689a7fb1b0053f5074f05a829d1ca9855da6
  - name: quay.io/nexodus/envsubst
    newTag: 41d9689a7fb1b0053f5074f05a829d1ca9855da6
  - name: quay.io/nexodus/frontend
    newTag: 41d9689a7fb1b0053f5074f05a829d1ca9855da6
  - name: quay.io/nexodus/go-ipam
    newTag: 41d9689a7fb1b0053f5074f05a829d1ca9855da6
