apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../openshift
  - sealed-secret.yaml
  - sealed-secret-smtp.yaml
namespace: nexodus
configMapGenerator:
  - behavior: replace
    literals:
      - hostname=auth.try.nexodus.io
      - frontend-url=https://try.nexodus.io
      - redirect-url=https://api.try.nexodus.io/web
    name: auth-config
  - behavior: replace
    files:
      - files/nexodus.json
    name: realm
  - behavior: merge
    literals:
      - APIPROXY_API_URL=https://api.try.nexodus.io
      - APIPROXY_OIDC_URL=https://auth.try.nexodus.io/realms/nexodus
      - APIPROXY_API_DOMAIN=api.try.nexodus.io
      - APIPROXY_WEB_DOMAIN=try.nexodus.io
        APIPROXY_AUTH_DOMAIN=auth.try.nexodus.io
      - APIPROXY_WEB_ORIGINS=https://try.nexodus.io
      - ENVOY_COMP_LOG_LEVEL=upstream:info,http:info,router:info,jwt:info
    name: apiproxy
  - behavior: merge
    literals:
      - NEXAPI_URL=https://api.try.nexodus.io
      - NEXAPI_OIDC_URL=https://auth.try.nexodus.io/realms/nexodus
      - NEXAPI_DOMAIN=api.try.nexodus.io
      - NEXAPI_ORIGINS=https://try.nexodus.io
      - NEXAPI_ENVIRONMENT=production
      - NEXAPI_FFLAG_SITES=false
      - NEXAPI_DEBUG=0
    name: apiserver

patches:
  # Update the dns names for the certificates
  - target:
      kind: Certificate
      name: nexodus-cert
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - try.nexodus.io
          - api.try.nexodus.io
          - auth.try.nexodus.io
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.try.nexodus.io
    target:
      kind: Ingress
      name: apiproxy
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: auth.try.nexodus.io
    target:
      kind: Ingress
      name: auth
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: try.nexodus.io
    target:
      kind: Ingress
      name: frontend
  - patch: |-
      - op: replace
        path: /spec/instances/0/dataVolumeClaimSpec/resources/requests/storage
        value: 8Gi
    target:
      kind: PostgresCluster
      name: database
