apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../released
  - issuer.yaml
  - sealed-secret.yaml
  - serviceaccount.yaml
components:
  - ../../components/promtail
  - ../../components/limitador
namespace: nexodus
configMapGenerator:
  - behavior: replace
    literals:
      - hostname=auth.try.nexodus.io
      - frontend-url=https://try.nexodus.io
    name: auth-config
  - behavior: replace
    files:
      - files/nexodus.json
    name: realm
  - behavior: merge
    literals:
      - APIPROXY_OIDC_URL=https://auth.try.nexodus.io/realms/nexodus
      - APIPROXY_API_DOMAIN=api.try.nexodus.io
      - APIPROXY_WEB_DOMAIN=try.nexodus.io
      - APIPROXY_WEB_ORIGINS=https://try.nexodus.io
      - ENVOY_COMP_LOG_LEVEL=upstream:info,http:info,router:info,jwt:info
    name: apiproxy
  - behavior: merge
    literals:
      - NEXAPI_OIDC_URL=https://auth.try.nexodus.io/realms/nexodus
      - NEXAPI_DOMAIN=api.try.nexodus.io
      - NEXAPI_REDIRECT_URL=https://try.nexodus.io/#/login
      - NEXAPI_ORIGINS=https://try.nexodus.io
      - NEXAPI_ENVIRONMENT=production
      - NEXAPI_DEBUG=0
    name: apiserver

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.try.nexodus.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.try.nexodus.io
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: apiproxy
  - patch: |-
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: nexodus-serviceaccount
    target:
      kind: Deployment
      name: apiproxy
  - patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
      - op: remove
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1ssl-passthrough
      - op: replace
        path: /spec/rules/0/host
        value: auth.try.nexodus.io
      - op: replace
        path: /spec/rules/0/http/paths/0/pathType
        value: ImplementationSpecific
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: ''
    target:
      kind: Ingress
      name: auth
  - patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: auth.try.nexodus.io
      - op: replace
        path: /spec/issuerRef/name
        value: letsencrypt
    target:
      kind: Certificate
      name: nexodus-auth-cert
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: try.nexodus.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: try.nexodus.io
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: frontend
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: promtail-role
    patch: |-
      - op: add
        path: /rules/1
        value: {"apiGroups":["security.openshift.io"],"resources":["securitycontextconstraints"],"resourceNames":["privileged"],"verbs":["use"]}
  - patch: |-
      - op: replace
        path: /spec/instances/0/dataVolumeClaimSpec/resources/requests/storage
        value: 6Gi
    target:
      kind: PostgresCluster
      name: database
