apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-providers
  namespace: nexodus
spec:
  encryptedData:
    GOOGLE_CLIENT_ID: AgCLC5s9NtyMANMaUJxcdgHF9aDGmqrwDoyL6Ij3ZiX/ZTTXr+Cbe3jcXvO5+hYBNdBJdEVtJRV7Vu+RqUJG+f8wWeU6JrfymQEHjV4qyzIMxfesToqBxHzvtY21qna+Qq4el8pH02JXr3Pu4hzjOnz79VX6a6N7lC4yrZ4GiOcp123bHEy72JKV2dOyeVSkMigq1Mgf2cUQlWdYd5Kux09Zca40FhhTrkIRocprpJOTNaojg5tjqgvmb5FroTzuTzi7+ZqnRF0J5BEIzqmQ7yglAs7zg2iQZw74CWSPUwIvUX8SWZVFsUfSE3m7yUslwnEv/2SGq23euK4UnwaFiALW1bJhjs3RSQptennppg/zlKV3s9WQw8YLBk504jhFC/NHA+/oGv/uluAqTXcf+GsmzRKpWU1OZA/54Q24VD2u2QUXzWgGLsLQJ9tsAMSUahCEt3/2HLw8SX76Wioj6xUx87lfa/wYIo52aoRzxVWchqetjIsI4wMrxw4Ys0vexCBGmZltpoLdS9FTnwWl8qU2DwS69SFuyY/3Z1qe3T9SlZb7fsdccwCu4DQrW6Rpormpx9tHBfDGn4/20YVygNeSnumEklpo1N6vQv0IWhvAqcDE4Ip4nEeomxz1b2IWWpJtRSOfOWViwhwHbolngeYxSKK9nznJ7z+12VGFHcs/WZoT9nQU1pLohca6tRCQWzZCkmslYNUl1Sii1bF9B5nO5V7t46buhFOPErEESuHvnuNoOnKn/YGIQvGA/SI3TUIygx+u5DeRi7GNP+67fe/FTu4Eswh2SIA=
    GOOGLE_CLIENT_SECRET: AgBazYLUttG/TJDxuYS+lHSeHi2GDDZ3ibHMnbI3CMq2XVuAwmoOQPatKlwF47FcH7MkMNbpr7pabVyDoHWlKQplvK/wWy2JFzWW6jtb7phJm4Ueh4oImRVbe7tDe0hCPOnoRnnomqaI4d6iYoPSHFu/E9O6o1RKTVLxldg0Yth4A/FFqcEoEC2LwvULv8xyeMz8kCPWGnGPEvBZHXiXfk0FgxQSydgIQtYG1Qub9WgMwFq/UB4K3DdFSWHIXSwu6mRFgf6+yUcew/BWJFtsEXpr20/TO+msX2vL1ftzSzQcl/8IrYWa2vT6c0S4LOrNw/f3yV/ctYhbbkaHx8n4ED9XPWCM/W26j1L5Yd0j+ZAtmveX3LMLusk1UsNi2p9LiPfKbY3vRPtbZ7EA5xeJeW7kDHgeoxik39SQcWmUA+uNP0NR0Huu38GWWAHIz5+o2E1h0QTZyPeGV9movwvOEhnz3tCKr1kyuOT8An6jUiTRqcrxMBOS4CjC4F6ZfHYdM/Yrimf23eQX1hfq6yy8gTubUieFyGpVetQN1Os7K9tqs37iKsu7GSzjIpR9Jfzn3qz6HOFFKmu3DnDjhFTwKzyQbHQRnutUHvfzsDnCCd29MLF7rMsLnzRwQx37ETMZ0JodKRarRlp4Rnce3/wbP4aLiEC18lsiyLuK/EHMKFKuL8S7nPptOrc5y5U+k7gFDR4I87Dc2dFIil67BkxY+bdpSMrGHcsqo0GFabG2wCPR+qrSpw==
  template:
    metadata:
      creationTimestamp: null
      name: auth-providers
      namespace: nexodus
