---
# tasks file for validate-connectivity-qa-containers
- name: Pause for 60 for convergence
  pause:
    seconds: 60

- name: Debug
  debug:
    msg: "Running connectivity test on spoke node: {{ inventory_hostname }}"

- name: Register the list of running containers
  become: yes
  command: docker ps -q
  register: container_ids

- name: Set a fact for the first container ID for connectivity tests
  set_fact:
    first_container_id: "{{ container_ids.stdout_lines[0] }}"

- name: Verify Connectivity from a spoke node to all spokes
  become: yes
  shell: |
    printf "====== Connectivity Results from Node: {{ inventory_hostname }} ======\n" >> {{ inventory_hostname }}-connectivity-results.txt
    docker exec {{ first_container_id }} nexctl nexd peers ping
    docker exec {{ first_container_id }} nexctl nexd peers ping  >> {{ inventory_hostname }}-connectivity-results.txt
    docker exec {{ first_container_id }} nexctl nexd peers ping6  >> {{ inventory_hostname }}-connectivity-results.txt
    cat {{ inventory_hostname }}-connectivity-results.txt
  ignore_errors: yes

# TODO: add this back after fixing the nexctl nexd peers list bug
#    printf "\n====== WG Dump from Node: {{ inventory_hostname }} ======\n" >> {{ inventory_hostname }}-connectivity-results.txt
#    nexctl nexd peers list >> {{ inventory_hostname }}-connectivity-results.txt 2>&1

- name: Print connectivity results
  debug:
    msg: "{{ result.stdout }}"

- name: Copy connectivity results back to the runner
  become: yes
  shell: "docker cp $(docker ps -l -q):/tmp/{{ inventory_hostname }}-connectivity-results.txt /home/{{ ansible_user }}/{{ inventory_hostname }}-connectivity-results.txt"

- name: Fetch connectivity results to Ansible control node
  fetch:
    src: "/home/{{ ansible_user }}/{{ inventory_hostname }}-connectivity-results.txt"
    dest: "./"
    flat: true

- name: Pause for debugging if specified in the github action dispatch
  pause:
    seconds: "{{ debug_pause | int * 60 }}"
  when: debug_pause is defined and debug_pause | int > 0
