---
# tasks file for validate-connectivity-qa-containers
- name: Pause for 60 for convergence
  pause:
    seconds: 60

- name: Debug
  debug:
    msg: "Running connectivity test on spoke node: {{ inventory_hostname }}"

# Run connections twice, once to stdout and one piped to a file.
- name: Verify Connectivity from a spoke node to all spokes
  become: yes
  shell: |
    printf "====== Connectivity Results from Node: {{ inventory_hostname }} ======\n" > connectivity-results.txt
    nexctl nexd peers ping
    nexctl nexd peers ping >> connectivity-results.txt 2>&1
    nexctl nexd peers ping6 >> connectivity-results.txt 2>&1
    printf "\n====== WG Dump from Node: {{ inventory_hostname }} ======\n" >> connectivity-results.txt
    nexctl nexd peers list >> connectivity-results.txt 2>&1
    cat connectivity-results.txt
  ignore_errors: yes

- name: Print connectivity results
  debug:
    msg: "{{ result.stdout }}"

- name: Copy connectivity results back to the runner
  become: yes
  shell: "docker cp $(docker ps -l -q):/tmp/connectivity-results.txt /home/{{ ansible_user }}/connectivity-results.txt"

- name: Fetch connectivity results to Ansible control node
  fetch:
    src: "/home/{{ ansible_user }}/connectivity-results.txt"
    dest: "./"
    flat: true

- name: Pause for debugging if specified in the github action dispatch
  pause:
    seconds: "{{ debug_pause | int * 60 }}"
  when: debug_pause is defined and debug_pause | int > 0
