apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiproxy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      initContainers:
        - args:
            - sh
            - -c
            - env; cat /configs/envoy-template/envoy.yaml | envsubst > /configs/envoy/envoy.yaml
          image: quay.io/nexodus/envsubst:latest
          imagePullPolicy: IfNotPresent
          name: envsubst
          env:
            - name: APIPROXY_OIDC_URL
              valueFrom:
                configMapKeyRef:
                  name: apiproxy
                  key: APIPROXY_OIDC_URL
            - name: APIPROXY_OIDC_BACKCHANNEL
              valueFrom:
                configMapKeyRef:
                  name: apiproxy
                  key: APIPROXY_OIDC_BACKCHANNEL
            - name: APIPROXY_API_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: apiproxy
                  key: APIPROXY_API_DOMAIN
            - name: APIPROXY_WEB_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: apiproxy
                  key: APIPROXY_WEB_DOMAIN
            - name: APIPROXY_WEB_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: apiproxy
                  key: APIPROXY_WEB_ORIGINS
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: envoy-config-template
              mountPath: /configs/envoy-template
            - name: envoy-config
              mountPath: /configs/envoy
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.27.0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          command:
            - envoy
            - --config-path
            - /configs/envoy/envoy.yaml
            - --component-log-level
            - $(ENVOY_COMP_LOG_LEVEL)
          env:
            - name: ENVOY_COMP_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: apiproxy
                  key: ENVOY_COMP_LOG_LEVEL
          ports:
            - name: api-envoy
              protocol: TCP
              containerPort: 9090
            - name: metrics-envoy
              protocol: TCP
              containerPort: 9000
          volumeMounts:
            - name: envoy-config
              mountPath: /configs/envoy
            - name: envoy-unix-sockets
              mountPath: /sockets
          readinessProbe:
            httpGet:
              path: /ready
              port: 9000
            periodSeconds: 5
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /ready
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
      restartPolicy: Always
      volumes:
        - name: envoy-config-template
          configMap:
            name: apiproxy-envoy-config
        - name: envoy-config
          emptyDir:
            medium: Memory
        - name: envoy-unix-sockets
          emptyDir:
            medium: Memory
