name: docs

on:
  push:
    branches: ["main"]
    paths:
      - '**/*.md'
      - '**/*.png'
      - '**/*.gitignore'
      - '.vscode/**'
      - '.excalidraw-ignore'
  pull_request:
    branches: ["main"]
    # Must stay in sync with the paths in .github/workflows/build.yml and .github/mergify.yml
    paths:
      - '**/*.md'
      - '**/*.png'
      - '**/*.gitignore'
      - '.vscode/**'
      - '.excalidraw-ignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: '**/*.md'

  png-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PNG Lint
        run: make png-lint

  docs-workflow-complete:
    needs: ["markdown-lint", "png-lint"]
    runs-on: ubuntu-latest
    steps:
      - name: Docs Workflow Complete
        run: echo "Docs Workflow Complete"
