name: docs

on:
  push:
    branches: ["main"]
    paths:
      - '**/*.md'
      - '**/*.png'
      - '**/*.gitignore'
      - '.vscode/**'
  pull_request:
    branches: ["main"]
    # Must stay in sync with the paths in .github/workflows/build.yml and .github/mergify.yml
    paths:
      - '**/*.md'
      - '**/*.png'
      - '**/*.gitignore'
      - '.vscode/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: '**/*.md'