name: promote

concurrency: prod-${{ github.ref_name }}

on:
  workflow_call:
  workflow_dispatch:

jobs:
  update-prod:
    name: Update Production Deployment
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the qa Tag
        uses: actions/checkout@v4
        with:
          ref: "qa"

      - name: Promote to the prod Tag
        shell: bash
        run: |
          git tag prod --force
          git push origin prod --force 
